feature/kart-saklama-prestashop kart saklama
kahvedigital/iyzico-prestashop pull request #1
Opened 2016-12-26 01:29 UTC by kahvedigital

2016-12-29 13:13 UTC, heheok requested changes
Yorum yaptığım satırları düzeltebilirsek merge edeceğim.

2016-12-29 13:13 UTC, heheok commented on cancel.php
> +    $options->setBaseUrl("https://api.iyzipay.com");
baseURL'in parametrik olması gerekmiyor mu? Yani kullanıcı panel'den sandbox seçerse bu adresin değişmesi gerekmiyor mu?

2016-12-29 13:13 UTC, heheok commented on config.xml
> +	<confirmUninstall><![CDATA[Are you sure about removing these details?]]></confirmUninstall>
Description'u türkçe yazmışız ama confirmUninstall ingilizce kalmış şu şekilde güncelleyebilir miyiz:
"Kaldırmak istediğinizden emin misiniz?"

2016-12-29 13:13 UTC, heheok commented on config_tr.xml
> +	<displayName><![CDATA[Iyzico Checkout Form]]></displayName>
iyzico'nun i harfi her zaman küçük olmalı.

2016-12-29 13:13 UTC, heheok commented on config.xml
> +	<displayName><![CDATA[Iyzico Checkout Form]]></displayName>
iyzico'nun i si küçük olmalı

2016-12-29 13:13 UTC, heheok commented on controllers/front/result.php
> +                $error_msg = ($language_iso_code == "tr") ? 'Jetonu bulunamadı.' : 'Token not found.';
"Jetonu bulunamadı." yerine "Güvenlik token'ı bulunamadı" yazalım

2016-12-29 13:13 UTC, heheok commented on controllers/front/result.php
> +            $error_msg = !empty($error_msg) ? $error_msg : 'Some error occured.Please try again.';
$error_msg 
site türkçe ise "Bir hata oluştu, lütfen tekrar deneyin."
site ingilizce ise "Unknown Error, please try again."

olmalı.

2016-12-29 13:13 UTC, heheok commented on controllers/front/result.php
> +            $error_msg = ($language_iso_code == "tr") ? 'indirim tutarını alışveriş tutarınızı karşılamıştır.' : 'The amount of the discount amounting to meet your shopping.'  ;
"indirim tutarını alışveriş tutarınızı karşılamıştır." yerine "Alışveriş tutarı indirim tutarına eşit olamaz."
"The amount of the discount amounting to meet your shopping." yerine "Cart total cannot be equal to discount amount"

2016-12-29 13:13 UTC, heheok commented on iyzicocheckoutform.php
> +        $this->displayName = $this->l('Iyzico Checkout Form');
İ küçük olmalı

2016-12-29 13:13 UTC, heheok commented on views/templates/hook/infos.tpl
> +<p><strong>{l s="Note: You can get your API ID and Secret Key values from https://merchant.iyzipay.com/settings." mod='iyzicocheckoutform'}</strong></p>
sayfanın üst kısmı türkçe bu satır ingilizce. Düzeltmek lazım.

2016-12-29 13:13 UTC, heheok commented on views/templates/hook/no_payment.tpl
> +            <a class="iyzicocheckoutform" href="{$success_url}" title="{l s='Iyzico ödeme formu' mod='iyzicocheckoutform'}">
iyzico'nun i'leri küçük

2016-12-29 13:13 UTC, heheok commented on views/templates/hook/order_detail.tpl
> +        <label>{l s="Iyzico Order History" mod='iyzicocheckoutform'} </label>
yine i

2017-01-17 20:00 UTC, kahvedigital commented on cancel.php
> +    $options->setBaseUrl("https://api.iyzipay.com");
Şuan Hiç bir modülde sandbox durumu olmadığından sabit vaziyette.

2017-01-17 20:19 UTC, kahvedigital commented on config.xml
> +	<confirmUninstall><![CDATA[Are you sure about removing these details?]]></confirmUninstall>
düzeltildi.

2017-01-17 20:19 UTC, kahvedigital commented on config.xml
> +	<displayName><![CDATA[Iyzico Checkout Form]]></displayName>
düzeltildi.

2017-01-17 20:19 UTC, kahvedigital commented on config_tr.xml
> +	<displayName><![CDATA[Iyzico Checkout Form]]></displayName>
düzeltildi.

2017-01-17 20:19 UTC, kahvedigital commented on controllers/front/result.php
> +                $error_msg = ($language_iso_code == "tr") ? 'Jetonu bulunamadı.' : 'Token not found.';
düzeltildi.

2017-01-17 20:19 UTC, kahvedigital commented on controllers/front/result.php
> +            $error_msg = !empty($error_msg) ? $error_msg : 'Some error occured.Please try again.';
düzeltildi.

2017-01-17 20:19 UTC, kahvedigital commented on controllers/front/result.php
> +            $error_msg = ($language_iso_code == "tr") ? 'indirim tutarını alışveriş tutarınızı karşılamıştır.' : 'The amount of the discount amounting to meet your shopping.'  ;
düzeltildi.

2017-01-17 20:19 UTC, kahvedigital commented on views/templates/hook/infos.tpl
> +<p><strong>{l s="Note: You can get your API ID and Secret Key values from https://merchant.iyzipay.com/settings." mod='iyzicocheckoutform'}</strong></p>
düzeltildi.

2017-01-17 20:19 UTC, kahvedigital commented on views/templates/hook/no_payment.tpl
> +            <a class="iyzicocheckoutform" href="{$success_url}" title="{l s='Iyzico ödeme formu' mod='iyzicocheckoutform'}">
düzeltildi.

2017-01-18 06:25 UTC, heheok approved these changes

2017-01-18 06:25 UTC, merged