feature/prestashop1.6-currency
kahvedigital/iyzico-prestashop pull request #8
Opened 2017-09-06 23:09 UTC by kahvedigital

currency

2017-09-07 10:17 UTC, heheok requested changes

2017-09-07 10:17 UTC, heheok commented on modules/iyzicocheckoutform/iyzicocheckoutform.php
> +error_reporting(1);
Error reporting'i kapatmak lazım.

2017-09-07 10:17 UTC, heheok commented on modules/iyzicocheckoutform/iyzicocheckoutform.php
> +            }
bu else'llere ihtiyacımız yoksa kullanmayalım.

2017-09-07 10:17 UTC, heheok commented on modules/iyzicocheckoutform/iyzicocheckoutform.php
> +           }
bu else'lere ihtiyacımız yoksa kullanmayalım.

2017-09-07 10:17 UTC, heheok commented on modules/iyzicocheckoutform/iyzicocheckoutform.php
> +
bu kadar boşluk bırakmayalım.

2017-09-07 10:17 UTC, heheok commented on modules/iyzicocheckoutform/iyzicocheckoutform.php
> +			if ($params['cookie']->is_guest !== 1) {
bu if'lerde hiç indent yok, okunabilir değil. düzenleyelim.

2017-09-07 23:23 UTC, kahvedigital commented
Değişiklikler yapıldı

2017-09-08 06:25 UTC, heheok approved these changes

2017-09-08 06:25 UTC, merged